#!/bin/bash

daemon()
{
	until [ ]; do
		python /home/pi/web-irsend/remote.py 2>/dev/null
		sleep 5
	done
}

daemonlog()
{
	until [ ]; do
		python /home/pi/web-irsend/remote.py >> /home/pi/web-irsend/log 2>&1
		sleep 5
	done
}

pids()
{
	ps auxwww | grep -v grep | grep web-irsend/remote.py | awk '{print $2}'
}

daemonpid()
{
	ps auxwww | grep -v grep | grep web-irsend/daemon | awk '{print $2}'
}

status()
{
	echo "Status:"
	ps auxwww | grep -v grep | grep web-irsend/remote.py
}

reset()
{
	status
	echo
	echo "Reset daemon:"
	sudo kill $(pids)
	echo
	status
}

stop()
{
	echo $(pids) $(daemonpid)
	sudo kill $(pids) $(daemonpid)
	echo $(pids) $(daemonpid)
}


if [ "$1" == "reset" ]; then
	reset
elif [ "$1" == "status" ]; then
	status
elif [ "$1" == "stop" ]; then
	stop
else
	daemon
fi



